### ISSUE TITLE
Pre-process script and save it

### ISSUE THREAD

**Issue by IngwiePhoenix** [fieryprophet/php-sandbox#20]
Hey there.

I am working on a project which needs to run PHP in a sub process and have internals changed. I know, this does not sound like a sandbox at first - but I am currently seeking for a solution for the problem described here:

https://github.com/christiaan/php-sandbox/issues/1#issuecomment-92073717

I could use runkit, but it is not a very optimal choice.

The code that will be ran through this sandbox is essentially huge. I want to run the Yii framework through it and I think, for performance, it would be good if I could "pre-compile" the scripts for the sandbox. Is that possible?

**Comment by fieryprophet** [comment]
You can prepare scripts for execution ahead of time by setting up a sandbox and using the prepare() method to return the generated code for caching. When you want to run the generated code you recreate the sandbox, use the set_code() method to fill in its generated code and call execute(). This will skip all the validation and preparsing steps and simply execute the prepared code directly.
