### ISSUE TITLE
How can i sandbox a include file

### ISSUE THREAD

**Issue by alexwenbj** [fieryprophet/php-sandbox#21]
For example:
$sandbox->excute(function(){
require_once("test.php");
});

If there is a blacklist function in the test.php,sandbox can't find it.

**Comment by fieryprophet** [comment]
Hey Alex,

This functionality has been integrated into the latest update. Set the flag $sandbox->allowed_includes to true.

**Comment by alexwenbj** [comment]
Thank you.
