### ISSUE TITLE
How to get the original code (line number) when eval()' code error occured

### ISSUE THREAD

**Issue by alexwenbj** [fieryprophet/php-sandbox#22]
Hi,When I used $sandbox->execute(function(){
//sandboxed code here
});
if the //sandboxed code here has an error,for example,use some variable named "abcdef" not defined before,it will return a notice like PHPSandbox.php(6919) : eval()'d code Undefined variable: abcdef.My question is:can I get the line number which the $abcdef located in original source code(means before sandbox eval()d),and how?

thanks.

**Comment by fieryprophet** [comment]
As far as I'm aware there's not a mechanism where the line of the evaluated code can be retrieved since evaluated code is run in a separate context from the surrounding sandbox.

**Comment by alexwenbj** [comment]
Got it.Thank you anyway.
