### ISSUE TITLE
Using variables to define functions for the sandbox.

### ISSUE THREAD

**Issue by pstephenson02** [fieryprophet/php-sandbox#23]
Hi,

I read through some of the other issues here, but I just want to confirm whether this is actually possible or not. I have some user created PHP code stored in my database that defines functions for which I would like to run in the sandbox. I've tried a number of ways...

```
        $sandbox = new \PHPSandbox\PHPSandbox();
        $sandbox->whitelist_keyword('function');
        $sandbox->set_option('allow_functions', true);
        $cc_func_name = $answer->getCodeChallenge()->getName(); // The function name
        $answerString = $answer->getAnswer(); // Function definition
        $sandbox->define_func($cc_func_name, $answerString);
        $sandbox->whitelist_func(array($cc_func_name, 'call_user_func_array'));

        $testCases = $answer->getCodeChallenge()->getTestCases();

        foreach ($testCases as $testCase) {
            if (count($testCase->getArgs()) > 1) {
                $args = $testCase->getArgs();
                $output = $sandbox->execute(function() {
                    return call_user_func_array($cc_func_name, $args);
                });

                // Compare $output to $testCase->output
            }
        }
```

I know that $sandbox->define_func() should take a callable function and I'm passing it a string, but is there some way to do this?

Thanks in advance

**Comment by fieryprophet** [comment]
This is exactly what the PHP builtin function create_function() is designed for:
http://php.net/manual/en/function.create-function.php

`$sandbox->define_func('test', create_func('$word', 'echo $word;'));`
