### ISSUE TITLE
Can the sandbox return detail parse err msg in cluded file

### ISSUE THREAD

**Issue by alexwenbj** [fieryprophet/php-sandbox#24]
Hi,If the sandbox execute function include a file,and the included file has a parse error,now it will return an error with msg "Could not parse sandboxed code!",can it return an error with the real error message?
For example:
...
$sandbox->execute(function(){
    include "test.php";
});
...
and the test.php is like:
...
echo "test";
invalid_str_here
...

could it return some error like:
"Parse error: syntax error, unexpected 'echo' (T_ECHO) in sandboxed_code.php on line 4."
rather than
"could not parse sandboxed code!"?

Thank you!

**Comment by fieryprophet** [comment]
After some research into this issue, I am afraid this isn't really feasible as invalid code fails as the parsing stage implemented by PHP-Parser, not the builtin PHP parsing engine, and therefore the native PHP error message is never invoked.

**Comment by alexwenbj** [comment]
Thank you！

发自我的 iPhone
