### ISSUE TITLE
http://www.fieryprophet.com/phpsandbox Down

### ISSUE THREAD

**Issue by ISaidHey** [fieryprophet/php-sandbox#30]
At the moment the site seems to be down so I can't access the manual and I don't see any mention of it here on GitHub so I wasn't sure if you were aware. I see the package comes with the Manual.html though so I guess this is more of a friendly poke then a real issue.

**Comment by avramovic** [comment]
Yes, the site is still down :( but you have `docs/index.html`, so I hope you can find what you need there.

**Comment by fieryprophet** [comment]
The library has been replaced with [Corveda/PHPSandbox](https://github.com/Corveda/PHPSandbox) and the website has moved to https://phpsandbox.org
