### ISSUE TITLE
Is it possible to parse PHP with html?

### ISSUE THREAD

**Issue by iamgoodbytes** [fieryprophet/php-sandbox#32]
Is it possible to parse something like this:

```I love eating
    <?php echo "appples"; ?>```

I'm building a learning tool for my students and while parsing PHP works out fine, I'm trying to figure out how to parse HTML mixed with php

**Comment by fieryprophet** [comment]
Unfortunately not, the underlying HTML is recognized by the PHP-Parser library only as an HTML fragment, it does not parse it further.

**Comment by iamgoodbytes** [comment]
Thanks for getting back to me! I guess I'll have to look for an alternative solution for my use case.
