### ISSUE TITLE
How to carry a context through repeated executions

### ISSUE THREAD

**Issue by datashaman** [fieryprophet/php-sandbox#33]
Hi, I can't find an answer to this anywhere in the docs: how to pass a context through repeat executions of different sandboxed code.

For example, on first execution, I define a variable:

```
$a = 'hello world';
```

Then on second execution, I echo it:

```
echo $a;
```

The sandbox appears to discard the context between executions. Is there a way to tell it to save the state so the second execution does not fail with `Undefined variable: a`?

**Comment by fieryprophet** [comment]
The sandbox does not save the execution context once it executes it, as PHP will clean up the state of the generated closure once it executes it. You can attempt to emulate this by saving the generated sandbox code using `$sandbox->getCode()` and then prepending it to the code you execute afterwards.

**Comment by fieryprophet** [comment]
Also, this package is no supported under this repository. For future reference, access this project at:

https://github.com/corveda/PHPSandbox
